query pokemonList(
  $where: pokemon_v2_pokemonspeciesname_bool_exp
  $limit: Int
  $offset: Int
  $pokemonV2TypenamesAggregateWhere2: pokemon_v2_typename_bool_exp
  $distinctOn: [pokemon_v2_pokemonspeciesname_select_column!]
  $pokemonV2PokemonsDistinctOn2: [pokemon_v2_pokemon_select_column!]
) {
  pokemon_v2_pokemonspeciesname_aggregate(
    where: $where
    limit: $limit
    offset: $offset
    distinct_on: $distinctOn
  ) {
    nodes {
      name
      genus
      pokemon_species_id
      pokemon_v2_pokemonspecy {
        pokemon_v2_pokemons(distinct_on: $pokemonV2PokemonsDistinctOn2) {
          pokemon_v2_pokemonsprites {
            sprites
          }
          pokemon_v2_pokemontypes {
            pokemon_v2_type {
              pokemon_v2_typenames_aggregate(
                where: $pokemonV2TypenamesAggregateWhere2
              ) {
                nodes {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
